import type { ComponentType } from "./types";

export const LAST_UPDATED = "2026-06";
export const PRICING_DISCLAIMER =
  "Prices and specs are approximate and illustrative, not a live price feed.";

export const catalog: ComponentType[] = [
  // ---- Accelerators ----
  {
    id: "gpu-nvidia-a100",
    name: "NVIDIA A100 80GB",
    category: "accelerator",
    vendor: "NVIDIA",
    specs: { trainingTFLOPS: 312, inferenceQPS: 1000, vramGB: 80, trainEff: 1.0, inferEff: 1.0, imageEff: 1.0 },
    capex: 10000,
    footprint: { rackUnits: 1, weightKg: 2 },
    powerDraw: 400,
    heatOutput: 400,
    description: "The workhorse data-center GPU of the early LLM era. Still capable and a bit cheaper than the H100, but a generation behind on speed.",
    learnMoreUrl: "https://en.wikipedia.org/wiki/Ampere_(microarchitecture)",
  },
  {
    id: "gpu-nvidia-h100",
    name: "NVIDIA H100 SXM",
    category: "accelerator",
    vendor: "NVIDIA",
    specs: { trainingTFLOPS: 1000, inferenceQPS: 3000, vramGB: 80, trainEff: 1.0, inferEff: 1.0, imageEff: 1.0 },
    capex: 30000,
    footprint: { rackUnits: 1, weightKg: 3 },
    powerDraw: 700,
    heatOutput: 700,
    description: "NVIDIA's flagship AI data-center GPU — very fast at both training and serving, but power-hungry (~700W) and expensive.",
    learnMoreUrl: "https://en.wikipedia.org/wiki/Hopper_(microarchitecture)",
  },
  {
    id: "gpu-amd-mi300x",
    name: "AMD Instinct MI300X",
    category: "accelerator",
    vendor: "AMD",
    specs: { trainingTFLOPS: 1300, inferenceQPS: 3200, vramGB: 192, trainEff: 1.0, inferEff: 1.0, imageEff: 1.0 },
    capex: 20000,
    footprint: { rackUnits: 1, weightKg: 3 },
    powerDraw: 750,
    heatOutput: 750,
    description: "AMD's answer to the H100 — a strong all-rounder with a lot of memory (192GB), often at a lower price.",
    learnMoreUrl: "https://en.wikipedia.org/wiki/AMD_Instinct",
  },
  {
    id: "acc-aws-trainium",
    name: "AWS Trainium",
    category: "accelerator",
    vendor: "AWS",
    specs: { trainingTFLOPS: 650, inferenceQPS: 500, vramGB: 96, trainEff: 1.0, inferEff: 0.4, imageEff: 0.4 },
    capex: 8000,
    footprint: { rackUnits: 1, weightKg: 2 },
    powerDraw: 500,
    heatOutput: 500,
    description: "Amazon's custom chip built specifically for training models cheaply — great at training, weak and wasteful for serving.",
    learnMoreUrl: "https://en.wikipedia.org/wiki/AI_accelerator",
  },
  {
    id: "acc-aws-inferentia",
    name: "AWS Inferentia",
    category: "accelerator",
    vendor: "AWS",
    specs: { trainingTFLOPS: 100, inferenceQPS: 2500, vramGB: 32, trainEff: 0.3, inferEff: 1.0, imageEff: 0.8 },
    capex: 5000,
    footprint: { rackUnits: 1, weightKg: 2 },
    powerDraw: 300,
    heatOutput: 300,
    description: "Amazon's custom chip tuned for inference — cheap and efficient at serving requests, but poor for training.",
    learnMoreUrl: "https://en.wikipedia.org/wiki/AI_accelerator",
  },
  {
    id: "acc-google-tpu",
    name: "Google TPU v5",
    category: "accelerator",
    vendor: "Google",
    specs: { trainingTFLOPS: 900, inferenceQPS: 2800, vramGB: 95, trainEff: 1.0, inferEff: 0.95, imageEff: 0.9 },
    capex: 15000,
    footprint: { rackUnits: 1, weightKg: 2 },
    powerDraw: 600,
    heatOutput: 600,
    description: "Google's Tensor Processing Unit — a custom AI chip that shines in large interconnected clusters for both training and serving.",
    learnMoreUrl: "https://en.wikipedia.org/wiki/Tensor_Processing_Unit",
  },
  // ---- CPU ----
  {
    id: "cpu-amd-epyc",
    name: "AMD EPYC 64-core",
    category: "cpu",
    vendor: "AMD",
    specs: { cores: 64, baseGHz: 2.4 },
    capex: 5000,
    footprint: { rackUnits: 1, weightKg: 1 },
    powerDraw: 300,
    heatOutput: 300,
    description: "A server CPU that runs the host system, feeds data to the accelerators, and handles everything that isn't raw AI math.",
    learnMoreUrl: "https://en.wikipedia.org/wiki/Epyc",
  },
  // ---- Server ----
  {
    id: "server-2u",
    name: "8-GPU Server (8U)",
    category: "server",
    vendor: "Generic",
    specs: { acceleratorSlots: 8, cpuSlots: 2, ramGB: 1024, rackUnits: 8 },
    capex: 8000,
    footprint: { rackUnits: 8, weightKg: 50 },
    powerDraw: 200,
    heatOutput: 200,
    description: "The chassis that holds up to 8 accelerators plus CPUs, memory, and fans. The box you actually slot chips into.",
    learnMoreUrl: "https://en.wikipedia.org/wiki/Server_(computing)",
  },
  // ---- Rack ----
  {
    id: "rack-42u",
    name: "42U Rack",
    category: "rack",
    vendor: "Generic",
    specs: { rackUnitCapacity: 42, powerCapacityKW: 30, weightCapacityKg: 1000 },
    capex: 2000,
    footprint: { areaSqM: 1.5, weightKg: 150 },
    powerDraw: 0,
    heatOutput: 0,
    description: "A standard cabinet that mounts servers and gear in stacked 'U' slots. Has limits on space, power, and weight.",
    learnMoreUrl: "https://en.wikipedia.org/wiki/19-inch_rack",
  },
  // ---- Power ----
  {
    id: "power-grid-feed",
    name: "Utility Grid Feed",
    category: "power",
    vendor: "Utility",
    specs: { capacityKW: 100, efficiency: 0.95, pricePerKWh: 0.1 },
    capex: 5000,
    footprint: { areaSqM: 2 },
    powerDraw: 0,
    heatOutput: 0,
    description: "The connection to the electrical grid that powers everything. Its capacity caps how much gear you can run, and electricity is the biggest monthly cost.",
    learnMoreUrl: "https://en.wikipedia.org/wiki/Electrical_grid",
  },
  {
    id: "power-ups",
    name: "UPS Battery Unit",
    category: "power",
    vendor: "Generic",
    specs: { capacityKW: 50, efficiency: 0.9 },
    capex: 15000,
    footprint: { rackUnits: 6, weightKg: 200 },
    powerDraw: 0,
    heatOutput: 0,
    description: "An uninterruptible power supply — battery backup that keeps gear running through brief outages so nothing crashes.",
    learnMoreUrl: "https://en.wikipedia.org/wiki/Uninterruptible_power_supply",
  },
  // ---- Cooling ----
  {
    id: "cooling-crac",
    name: "CRAC Air Unit",
    category: "cooling",
    vendor: "Generic",
    specs: { heatRemovalKW: 50 },
    capex: 20000,
    footprint: { areaSqM: 2, weightKg: 300 },
    powerDraw: 15000,
    heatOutput: 0,
    description: "A Computer Room Air Conditioner — blows cold air to carry heat out of the room so the chips don't cook. Uses power itself.",
    learnMoreUrl: "https://en.wikipedia.org/wiki/Computer_room_air_conditioning",
  },
  {
    id: "cooling-liquid",
    name: "Liquid Cooling Loop",
    category: "cooling",
    vendor: "Generic",
    specs: { heatRemovalKW: 150 },
    capex: 60000,
    footprint: { areaSqM: 2, weightKg: 250 },
    powerDraw: 20000,
    heatOutput: 0,
    description: "Pumps liquid right past the chips to remove far more heat than air — essential for dense, high-power GPU clusters.",
    learnMoreUrl: "https://en.wikipedia.org/wiki/Computer_cooling",
  },
  // ---- Network ----
  {
    id: "net-tor-switch",
    name: "Top-of-Rack Switch",
    category: "network",
    vendor: "Generic",
    specs: { bandwidthGbps: 800, ports: 48 },
    capex: 12000,
    footprint: { rackUnits: 1, weightKg: 10 },
    powerDraw: 500,
    heatOutput: 500,
    description: "Connects the servers within a rack so they can talk to each other and the rest of the data center.",
    learnMoreUrl: "https://en.wikipedia.org/wiki/Network_switch",
  },
  {
    id: "net-spine-switch",
    name: "Spine Switch",
    category: "network",
    vendor: "Generic",
    specs: { bandwidthGbps: 3200, ports: 64 },
    capex: 40000,
    footprint: { rackUnits: 2, weightKg: 15 },
    powerDraw: 1200,
    heatOutput: 1200,
    description: "A high-bandwidth backbone switch that ties many racks together — what lets thousands of chips train as one cluster.",
    learnMoreUrl: "https://en.wikipedia.org/wiki/Network_switch",
  },
  // ---- Space ----
  {
    id: "space-floor-tile",
    name: "Data Hall Floor Tile",
    category: "space",
    vendor: "N/A",
    specs: { areaSqM: 10, powerDensityCapKWperSqM: 5 },
    capex: 1000,
    footprint: { areaSqM: 10 },
    powerDraw: 0,
    heatOutput: 0,
    description: "Physical floor space in the building. Land and floor area cap how much you can fit, and there's a limit to how much power each square meter can handle.",
    learnMoreUrl: "https://en.wikipedia.org/wiki/Data_center",
  },
];
